# Generated by Django 6.0 on 2026-01-03 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='banner',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
