# Generated by Django 6.0 on 2026-01-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.CharField(blank=True, help_text='Duration in MM:SS format', max_length=10),
        ),
    ]
