# Generated by Django 6.0 on 2026-01-01 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
    ]
